sudo: false

jobs:
  include:
    - stage: compile
      dist: bionic
      language: cpp
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - g++
            - lcov
      script:
        - ./configure.sh
        - pushd out
        - make
    - stage: tests
      dist: bionic
      language: cpp
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - g++
            - lcov
      script:
        - ./configure.sh
        - pushd out
        - make
        - ./MoreModbusTests
    - stage: deploy
      if: branch = master
      branches:
        only:
          - master
      addons:
        apt:
          packages:
            - doxygen
      script:
        - doxygen Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
